### ISSUE TITLE
Improvements on $libdir/postgis-2.2

### ISSUE THREAD

**Issue by psychok7** [appropriate/docker-postgis#58] opened 2017-06-30 11:45 UTC
I started getting `could not access file "$libdir/postgis-2.2": No such file or directory` a couple of days ago on my `mdillon/postgis:9.5-alpine` image and even after i ran `docker exec some-postgis update-postgis.sh` it did not work for me because it was complaining about `ERROR:  extension "postgis_tiger_geocoder" does not exist`.

Digging a bit further i found that the current `update-postgis.sh` ( https://github.com/appropriate/docker-postgis/commit/25373b2d608fdd65af8f8d0c05e4ab1caa2e3f4a#diff-be90b6e0b4f64886cc3f7c44e5670e07 ) does not take into account a "fresh database" created by the final user without `postgis_tiger_geocoder` which was my case.

So to fix it i just entered my database and manually ran the commands (without caring about `postgis_tiger_geocoder`):

```sql
postgres=# SELECT PostGIS_full_version();
ERROR:  could not access file "$libdir/postgis-2.2": No such file or directory
CONTEXT:  SQL statement "SELECT postgis_lib_version()"
PL/pgSQL function postgis_full_version() line 22 at SQL statement
postgres=# ALTER EXTENSION postgis  UPDATE TO '2.3.2';
ALTER EXTENSION
postgres=# ALTER EXTENSION postgis_topology UPDATE TO '2.3.2';
ALTER EXTENSION
postgres=# SELECT PostGIS_full_version(); 
```

This fixed it for me, but as an improvement maybe we could make the `update-postgis.sh` ensure the extensions are already created before trying to Alter them and failing in doing so.

UPDATE:

This happened to me again and to fix it i:

```sql
ALTER EXTENSION postgis UPDATE;
ALTER EXTENSION postgis_topology UPDATE;
```

**Comment by jmagnusson** [comment] 2017-11-10 10:39
I had the same issue just now, after `mdillon/postgis:9.6-alpine` had the postgis version updated to 2.4.0. The solution for me was to run this manually before running `update-postgis.sh`:

```shell
psql --dbname="$DB" \
     -c "CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder; \
         CREATE EXTENSION IF NOT EXISTS postgis_topology;"
```

@md5 Perhaps all the `CREATE EXTENSION` statements should be added to `update-postgis.sh` to avoid this happening in future releases.

**Comment by md5** [comment] 2017-11-10 18:57
@jmagnusson That seems reasonable.

@psychok7 It should be possible to check `pg_extension` to see which extensions are installed and which version they are before proceeding with any `ALTER EXTENSION` statements.

**Comment by md5** [comment] 2017-11-11 05:51
Can you guys have a look at this: https://github.com/appropriate/docker-postgis/pull/70

**Comment by msalahz** [comment] 2017-11-11 13:56
Any updates about this ?

**Comment by md5** [comment] 2017-11-11 15:07
@mshalaz other than the PR I opened yesterday?

**Comment by msalahz** [comment] 2017-11-11 19:12
Hi @md5 : I meant can we merge this any time soon ?
My staging is not functional after last release and I cannot release to production anymore due to this error and I need it it merged ASAP please because i'm not a postgis expert.

**Comment by md5** [comment] 2017-11-12 14:57
@msalahz That PR updates a script called `update-postgis.sh`. Since that script doesn't run automatically, merging that PR won't do anything for you that you can't do manually by just running the commands in the file.

**Comment by psychok7** [comment] 2017-11-13 11:00
@md5 this happened to me again because we reinstalled docker and downloaded new images that mismatched with the postgis in our db/volume.

Any ideas when you are going to merge and release https://github.com/appropriate/docker-postgis/pull/70

**Comment by klinden** [comment] 2017-11-16 18:56
Is there any reason update-postgis.sh couldn't be run automatically? Perhaps by copying it to `/docker-entrypoint-initdb.d`?

**Comment by md5** [comment] 2017-11-16 20:02
@klinden I'm not sure. Given the difficulties in even maintaining reliable tagging and a reproducible image, I'm not sure I want to add any more variability to how the image works.

**Comment by JacobHayes** [comment] 2017-11-22 20:13
Adding to `docker-entrypoint-initdb.d` wouldn't help - as named, those scripts are only called on db creation. Short of tweaking the main entrypoint (from the parent image), the script will have to be called out of band. In my case, I'm using two `ExecStartPost`s in my systemd service to run it. The first is a loop waiting for the database to startup and the second runs this script. Ex:

```
ExecStartPost=/bin/sh -c 'until /usr/bin/docker exec --user=postgres postgres psql -c "select 1"; do /usr/bin/sleep 2; done;'
ExecStartPost=/usr/bin/docker exec --user=postgres postgres update-postgis.sh
```

**Closed** 2018-10-03 06:45 UTC
